name: multiple_attach_test
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.multiple_attach_test
        pluginClass: MultipleAttachTestPlugin
